version: "3.9"
services:
  swagger-ui:
    image: "swaggerapi/swagger-ui"
    ports:
      - "${LOCAL_PORT}:8080"
    env_file:
      - "${ENV_FILE_NAME}"
    volumes:
      - "${LOCAL_VOLUME_PATH}:${CONTAINER_VOLUME_PATH}"